# Generated by Django 6.0.1 on 2026-01-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Delhi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(default=450331),
            preserve_default=False,
        ),
    ]
