# Generated by Django 6.0.1 on 2026-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_customer_city_customer_name_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
