# Generated by Django 6.0.1 on 2026-01-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_location',
            field=models.CharField(default='Seller Warehouse', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Placed'), ('Packed', 'Packed & Ready'), ('Shipped', 'On the Way (Shipped)'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
